// Unity build generated by CMake

#pragma message ("[1/30] Compiling Localisation.cpp...")
#include "C:/Code/Git/arx-libertatis-Remix/arx/src/core/Localisation.cpp"

#pragma message ("[2/30] Compiling Blast.cpp...")
#include "C:/Code/Git/arx-libertatis-Remix/arx/src/io/Blast.cpp"

#pragma message ("[3/30] Compiling IniReader.cpp...")
#include "C:/Code/Git/arx-libertatis-Remix/arx/src/io/IniReader.cpp"

#pragma message ("[4/30] Compiling IniSection.cpp...")
#include "C:/Code/Git/arx-libertatis-Remix/arx/src/io/IniSection.cpp"

#pragma message ("[5/30] Compiling SaveBlock.cpp...")
#include "C:/Code/Git/arx-libertatis-Remix/arx/src/io/SaveBlock.cpp"

#pragma message ("[6/30] Compiling FilePath.cpp...")
#include "C:/Code/Git/arx-libertatis-Remix/arx/src/io/fs/FilePath.cpp"

#pragma message ("[7/30] Compiling FileStream.cpp...")
#include "C:/Code/Git/arx-libertatis-Remix/arx/src/io/fs/FileStream.cpp"

#pragma message ("[8/30] Compiling Filesystem.cpp...")
#include "C:/Code/Git/arx-libertatis-Remix/arx/src/io/fs/Filesystem.cpp"

#pragma message ("[9/30] Compiling FilesystemWindows.cpp...")
#include "C:/Code/Git/arx-libertatis-Remix/arx/src/io/fs/FilesystemWindows.cpp"

#pragma message ("[10/30] Compiling SystemPaths.cpp...")
#include "C:/Code/Git/arx-libertatis-Remix/arx/src/io/fs/SystemPaths.cpp"

#pragma message ("[11/30] Compiling ConsoleLogger.cpp...")
#include "C:/Code/Git/arx-libertatis-Remix/arx/src/io/log/ConsoleLogger.cpp"

#pragma message ("[12/30] Compiling LogBackend.cpp...")
#include "C:/Code/Git/arx-libertatis-Remix/arx/src/io/log/LogBackend.cpp"

#pragma message ("[13/30] Compiling Logger.cpp...")
#include "C:/Code/Git/arx-libertatis-Remix/arx/src/io/log/Logger.cpp"

#pragma message ("[14/30] Compiling MsvcLogger.cpp...")
#include "C:/Code/Git/arx-libertatis-Remix/arx/src/io/log/MsvcLogger.cpp"

#pragma message ("[15/30] Compiling PakEntry.cpp...")
#include "C:/Code/Git/arx-libertatis-Remix/arx/src/io/resource/PakEntry.cpp"

#pragma message ("[16/30] Compiling PakReader.cpp...")
#include "C:/Code/Git/arx-libertatis-Remix/arx/src/io/resource/PakReader.cpp"

#pragma message ("[17/30] Compiling ResourcePath.cpp...")
#include "C:/Code/Git/arx-libertatis-Remix/arx/src/io/resource/ResourcePath.cpp"

#pragma message ("[18/30] Compiling Dialog.cpp...")
#include "C:/Code/Git/arx-libertatis-Remix/arx/src/platform/Dialog.cpp"

#pragma message ("[19/30] Compiling Environment.cpp...")
#include "C:/Code/Git/arx-libertatis-Remix/arx/src/platform/Environment.cpp"

#pragma message ("[20/30] Compiling Lock.cpp...")
#include "C:/Code/Git/arx-libertatis-Remix/arx/src/platform/Lock.cpp"

#pragma message ("[21/30] Compiling OS.cpp...")
#include "C:/Code/Git/arx-libertatis-Remix/arx/src/platform/OS.cpp"

#pragma message ("[22/30] Compiling Platform.cpp...")
#include "C:/Code/Git/arx-libertatis-Remix/arx/src/platform/Platform.cpp"

#pragma message ("[23/30] Compiling ProgramOptions.cpp...")
#include "C:/Code/Git/arx-libertatis-Remix/arx/src/platform/ProgramOptions.cpp"

#pragma message ("[24/30] Compiling Time.cpp...")
#include "C:/Code/Git/arx-libertatis-Remix/arx/src/platform/Time.cpp"

#pragma message ("[25/30] Compiling String.cpp...")
#include "C:/Code/Git/arx-libertatis-Remix/arx/src/util/String.cpp"

#pragma message ("[26/30] Compiling SaveFix.cpp...")
#include "C:/Code/Git/arx-libertatis-Remix/arx/tools/savetool/SaveFix.cpp"

#pragma message ("[27/30] Compiling SaveFix.h...")
#include "C:/Code/Git/arx-libertatis-Remix/arx/tools/savetool/SaveFix.h"

#pragma message ("[28/30] Compiling SaveTool.cpp...")
#include "C:/Code/Git/arx-libertatis-Remix/arx/tools/savetool/SaveTool.cpp"

#pragma message ("[29/30] Compiling SaveView.cpp...")
#include "C:/Code/Git/arx-libertatis-Remix/arx/tools/savetool/SaveView.cpp"

#pragma message ("[30/30] Compiling SaveView.h...")
#include "C:/Code/Git/arx-libertatis-Remix/arx/tools/savetool/SaveView.h"

