// Unity build generated by CMake

#pragma message ("[1/22] Compiling Blast.cpp...")
#include "C:/Code/Git/arx-libertatis-Remix/arx/src/io/Blast.cpp"

#pragma message ("[2/22] Compiling FilePath.cpp...")
#include "C:/Code/Git/arx-libertatis-Remix/arx/src/io/fs/FilePath.cpp"

#pragma message ("[3/22] Compiling FileStream.cpp...")
#include "C:/Code/Git/arx-libertatis-Remix/arx/src/io/fs/FileStream.cpp"

#pragma message ("[4/22] Compiling Filesystem.cpp...")
#include "C:/Code/Git/arx-libertatis-Remix/arx/src/io/fs/Filesystem.cpp"

#pragma message ("[5/22] Compiling FilesystemWindows.cpp...")
#include "C:/Code/Git/arx-libertatis-Remix/arx/src/io/fs/FilesystemWindows.cpp"

#pragma message ("[6/22] Compiling SystemPaths.cpp...")
#include "C:/Code/Git/arx-libertatis-Remix/arx/src/io/fs/SystemPaths.cpp"

#pragma message ("[7/22] Compiling ConsoleLogger.cpp...")
#include "C:/Code/Git/arx-libertatis-Remix/arx/src/io/log/ConsoleLogger.cpp"

#pragma message ("[8/22] Compiling LogBackend.cpp...")
#include "C:/Code/Git/arx-libertatis-Remix/arx/src/io/log/LogBackend.cpp"

#pragma message ("[9/22] Compiling Logger.cpp...")
#include "C:/Code/Git/arx-libertatis-Remix/arx/src/io/log/Logger.cpp"

#pragma message ("[10/22] Compiling MsvcLogger.cpp...")
#include "C:/Code/Git/arx-libertatis-Remix/arx/src/io/log/MsvcLogger.cpp"

#pragma message ("[11/22] Compiling PakEntry.cpp...")
#include "C:/Code/Git/arx-libertatis-Remix/arx/src/io/resource/PakEntry.cpp"

#pragma message ("[12/22] Compiling PakReader.cpp...")
#include "C:/Code/Git/arx-libertatis-Remix/arx/src/io/resource/PakReader.cpp"

#pragma message ("[13/22] Compiling ResourcePath.cpp...")
#include "C:/Code/Git/arx-libertatis-Remix/arx/src/io/resource/ResourcePath.cpp"

#pragma message ("[14/22] Compiling Dialog.cpp...")
#include "C:/Code/Git/arx-libertatis-Remix/arx/src/platform/Dialog.cpp"

#pragma message ("[15/22] Compiling Environment.cpp...")
#include "C:/Code/Git/arx-libertatis-Remix/arx/src/platform/Environment.cpp"

#pragma message ("[16/22] Compiling Lock.cpp...")
#include "C:/Code/Git/arx-libertatis-Remix/arx/src/platform/Lock.cpp"

#pragma message ("[17/22] Compiling OS.cpp...")
#include "C:/Code/Git/arx-libertatis-Remix/arx/src/platform/OS.cpp"

#pragma message ("[18/22] Compiling Platform.cpp...")
#include "C:/Code/Git/arx-libertatis-Remix/arx/src/platform/Platform.cpp"

#pragma message ("[19/22] Compiling ProgramOptions.cpp...")
#include "C:/Code/Git/arx-libertatis-Remix/arx/src/platform/ProgramOptions.cpp"

#pragma message ("[20/22] Compiling Time.cpp...")
#include "C:/Code/Git/arx-libertatis-Remix/arx/src/platform/Time.cpp"

#pragma message ("[21/22] Compiling String.cpp...")
#include "C:/Code/Git/arx-libertatis-Remix/arx/src/util/String.cpp"

#pragma message ("[22/22] Compiling UnPak.cpp...")
#include "C:/Code/Git/arx-libertatis-Remix/arx/tools/unpak/UnPak.cpp"

